"""
Sheep's clothing, wolfish impact - Research artifact for studying acceptable ads and their impact on user privacy
Copyright (C) 2025  Ritik Roongta

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import base64
from openai import OpenAI
import os
import pandas as pd
import json
import requests
import sys
import re
import time
import glob
import argparse

def get_api_key():
    """Get OpenAI API key from environment variable or command line argument."""
    parser = argparse.ArgumentParser(description='LLM annotation for ad analysis')
    parser.add_argument('--openai_key', type=str, help='OpenAI API key')
    parser.add_argument('--openai-key', type=str, help='OpenAI API key (alternative format)')
    args, _ = parser.parse_known_args()
    
    # Try command line argument first
    api_key = args.openai_key or args.openai_key
    
    # Fall back to environment variable
    if not api_key:
        api_key = os.getenv("OPENAI_KEY")
    
    if not api_key:
        raise ValueError("OpenAI API key not found. Please provide it via --openai_key argument or set the OPENAI_KEY environment variable.")
    
    return api_key

# Initialize OpenAI API with your key
api_key = get_api_key()

# Initialize OpenAI client
client = OpenAI(api_key=api_key)

def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')
    
def check_dp(strr):
    # check if an alphanumeric character is followed by a '...' or ' ...' ('a  ...' should not be considered)
    # return True if found, False otherwise
    pattern = r"\w(?:(?<! )\.\.\.| \.\.\.)"
    return bool(re.search(pattern, strr))

def get_ad_images():
    """Get all ad images from the crawl data"""
    ad_images = []
    
    # Get adblock images
    adblock_images = glob.glob('./data/adblock/adshots/*.png')
    for img_path in adblock_images:
        filename = os.path.basename(img_path)
        ad_images.append({
            'path': img_path,
            'filename': filename,
            'type': 'adblock',
            'full_path': img_path
        })
    
    # Get control images
    control_images = glob.glob('./data/control/adshots/*.png')
    for img_path in control_images:
        filename = os.path.basename(img_path)
        ad_images.append({
            'path': img_path,
            'filename': filename,
            'type': 'control',
            'full_path': img_path
        })
    
    return ad_images

all_annot = {}
explanations = {}

# Get all ad images
ad_images = get_ad_images()
print(f"Found {len(ad_images)} ad images to annotate")

patterns = ['\bsearches', '\bsearch for\b', '\bsearch ad', '\bgosearch', '\bsearchtopics\b', 'suv deals', '\bsuchergebnisse\b', '\bsuchanzeigen\b']

for i, img_info in enumerate(ad_images):
    print(f"Processing {i+1}/{len(ad_images)}: {img_info['filename']}")
    
    image_path = img_info['full_path']
    filename = img_info['filename']
    img_type = img_info['type']
    
    # Load OCR text from the JSON files generated by the processing service
    ocr_text = ""
    ocr_file_path = f'../image_hashing/ocr_{img_type}.json'
    if os.path.exists(ocr_file_path):
        try:
            with open(ocr_file_path, 'r') as f:
                ocr_data = json.load(f)
                if filename in ocr_data:
                    ocr_text = ocr_data[filename]
                    print(f"Loaded OCR text for {filename}: {ocr_text[:100]}...")
                else:
                    print(f"No OCR data found for {filename}")
        except Exception as e:
            print(f"Error loading OCR data for {filename}: {e}")
    else:
        print(f"OCR file not found: {ocr_file_path}")
    
    try:
        base64_image = encode_image(image_path)
        
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages = [
            {
                "role": "user",
                "content": 
                    [
                        {  
                            "type": "text",
                            "text": """Analyze the attached ad and determine if it is problematic or non-problematic strictly based on the taxonomy. If problematic, return the category title you find it to be belonging to as the key value. Otherwise return an empty string as the key value. Analyse all possible sub ad images present as well."""
                        },
                        {
                            "type": "text",
                            "text": f"{ocr_text}"
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url":  f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
            },
            {
                "role": "system",
                "content":
                    """You are an expert in evaluating online display advertisements based on a taxonomy derived from ad exchange policies and user perception studies. Analyze the provided advertisement screenshot to determine if it is problematic, strictly using the provided taxonomy. For the ad images, you should also identify advertiser information. 
                    ##
                    **Advertiser information**:
                    Extract the advertiser's name from visible brand logos, text, or symbols in the ad image -- looking for unique fonts, stylized text, distinct colors, or logo designs that stand out from the main content.
                    - For Taboola and Outbrain ads, consider the advertiser as the publisher's name below each ad title. 
                    - Ads with obscure advertiser names that resemble english sentences should be categorized as *logo*.
                    - Ad screenshots with multiple advertisers should be classified as *multiple advertisers*. 
                    ## 
                    The text present (OCR output) in the ad creative is also provided as an additional input for processing and identifying any problematic behaviour.
                    ##
                    The taxonomy includes a title, definition, keywords, and notes for each category. Strictly use the definitions, keywords, and notes as primary guides. The keywords are exhaustive and represent the themes covered in each category.  
                    ##  
                    Be conservative in your classification: Only classify if the ad clearly and confidently fits a category. If in doubt, classify it as non-problematic.   
                    ##
                    Since it is a multi-label classification, multiple categories can be chosen. Return a JSON object with the following structure:  
                    1. A `categories` key containing a list of applicable categories. If non-problematic, return an empty list as the value.  
                    2. An `explanations` key providing a rationale for each identified category. Include detailed reasoning for each flagged category.
                    3. An `advertiser` key containing the advertiser name identified in the ad image. If multiple ads exist, report 'multiple advertiser'. If no advertiser identification is possible or no subtitle is present, report *None* in the value.  
                    ##  
                    For screenshots with multiple ads, return the superset of categories covering all ads.
                    ###
                    Taxonomy:
                    1. Regulations
                    Definition: Ads deemed inappropriate for younger audiences (Below 18 years) due to product or content nature. 
                    Keywords: sexually suggestive, Cannabinoids, alcohol, gambling/sweepstakes, cosmetic interventions, hazardous goods, drug use, Weight-reduction regimes or establishments, Lottery, E-Cigarettes, Prescription-only medicines, Dating sites
                    #
                    Note: 
                    - Classify only if clear evidence like explicit exposure, provocative poses, or overtly suggestive context exists; avoid bias towards modeling images. 
                    - Sexually suggestive ads should be classified into both `Regulations` and `Inappropriate or Offensive Content` if the content is derogatory or explicit.
                    ##
                    2. Inappropriate or Offensive Content
                    Definition: Ads containing language, visuals, or themes that are offensive, hateful, or disrespectful towards general public and not focused groups.
                    Keywords: Sexually explicit, offensive language, violent acts, hate speech, hookup, graphic images, racially insensitive, conspiracy theories, disrespectful religious/sacred content/profanity, trafficking, social issues, hacking
                    #
                    Note: 
                    - Merely mentioning potentially sensitive topics (e.g., violence, religion) does not automatically make the ad offensive unless it is presented in a disturbing, demeaning, or shocking manner.
                    - References to advertiser or domain names that contain edgy words or horror themes are not automatically classified as offensive.
                    ##
                    3. Deceptive Claims and Exaggerated Benefits 
                    Definition: Ads that make unverified or exaggerated claims about a product's or service's effectiveness, often with the intent to mislead consumers. Unlike Dark Patterns, these ads include specific claims in their content, rather than relying solely on clickbait tactics.
                    Keywords: 
                        Health claims - No disclosure, Reasons for conditions, miracle cure, weight loss, scientifically proven, Dietary supplements, cosmetic beauty treatments, mental health services, false vaccine information, cheap substitutes
                        Financial Claims - get rich quick, financial freedom, investment returns, guaranteed profits, False Tax Promises, Crypto Gain Misrepresentation, debt relief
                        Environmental Claims - No disclosure, greenwashing (eco-friendly, sustainable, green product, carbon-neutral, environmentally safe), eco-friendly, ethical sourcing, organic, waste reduction claims
                        Other Impossible Claims - overpromising, instant results, transform your life, best in the world/market, one-of-a-kind, never-before-seen, guaranteed satisfaction, exclusive deal, legal claims
                    #
                    Note: 
                    - No disclosures are required for finance-related ads offering incentives like 'up to a certain amount' for account openings. 
                    - Focus on identifying financial claims that appear fraudulent or excessively unrealistic, rather than scrutinizing all claims.
                    ##
                    4. Dark Patterns and Manipulative Design
                    Definition: Ads that use deceptive design techniques to manipulate user behavior, such as clicking, subscribing, or sharing information unintentionally.
                    Keywords: clickbait, social engineering, scarcity tactics, confirmshaming, countdown timers, fake buttons, sensationalism, fake testimonials, fake celebrity endorsements, urgency, last chance, your data is at risk, fear tactics, emergency, danger, don't miss out, Incomplete sentences using ...
                    #
                    Note: 
                    - Fake or multiple buttons present in the Ad image should be classified as *Dark Patterns and Manipulative Design*.
                    - Search ads with multiple clickable rows should be classified as *Dark Patterns and Manipulative Design* 
                    ##
                    5. User Experience Disruption  
                    Definition: Ads that degrade the user experience by being overly intrusive, misleading, repetitive, or lck of advertiser information. This includes ads with unnatural, or highly manipulated imagery that causes confusion or doubt about authenticity.  
                    Keywords: annoying, intrusive (revealing locations), auto-playing video, difficult-to-close pop-ups, disruptive ad formats, ad loading speed, unclear labeling of sponsored content. Ad quality (image), No Information (text/image) - for context.  
                    #
                    Note:
                    - Ads containing **map snippets** that indicate proximity to the user's location are considered intrusive, classify them as **User Experience Disruption**.
                    - Different ads with **identical images** within the ad screenshot, are classified them as **User Experience Disruption**. Multiple but different ads appearing in the same screenshot are not disruption.
                    - Ignore popup notifications originating from or local to the website itself.
                    ##
                    6. Political and Socially Sensitive Topics
                    Definition: Ads related to political topics that could polarize or manipulate public opinion, especially during sensitive times like elections.
                    Keywords: No disclosure (endorsements), election campaigns, fake endorsements, fake news, propaganda (climate change, LGBTQ rights, racial justice, religious freedom, abortion, immigration policy), defaming candidates
                    #
                    Note: 
                    - Classify specific propaganda ads if the content undermines trust or portrays a person or entity in a detrimental or questionable manner.
                    """
            },
            ],
            temperature=0,
            response_format={'type':'json_object'}
        )

        res = response.choices[0].message.content
    except Exception as e:
        print(f'ERROR processing {filename}:', e)
        res = "{}"

    try:
        res = json.loads(res)
        if "explanations" not in res.keys():
            res["explanations"] = {}
        elif type(res["explanations"]) == list:
            res["explanations"] = {}

        # Add Dark patterns due to '...'
        if check_dp(ocr_text) and 'Dark Patterns and Manipulative Design' not in res['categories']:
            res["categories"].append('Dark Patterns and Manipulative Design')
            res["explanations"]['dp'] = "DP artificially added"
        
        # Add User Experience Disruption due to brand name not being present
        if res['advertiser'] == 'None' or any(re.search(pattern, ocr_text.lower()) for pattern in patterns):
            if 'User Experience Disruption' not in res["categories"]:
                res["categories"].append('User Experience Disruption')
                res["explanations"]['ued'] = 'UED artifically added'

        print(f"Result for {filename}: {res}")
        all_annot[image_path] = ';'.join(res["categories"])
        explanations[image_path] = res["explanations"]
        
        # Save progress after each image
        json.dump(all_annot, open('llm_annotation_dict_4o.json', 'w'))
        json.dump(explanations, open('llm_annotation_explanations_4o.json', 'w'))

    except Exception as e:
        print(f'ERROR parsing result for {filename}:', e, res)
        all_annot[image_path] = res
        explanations[image_path] = res

# Create a summary DataFrame
results_data = []
for img_info in ad_images:
    image_path = img_info['full_path']
    filename = img_info['filename']
    img_type = img_info['type']
    
    annotation = all_annot.get(image_path, 'ERROR')
    explanation = explanations.get(image_path, {})
    
    results_data.append({
        'filename': filename,
        'type': img_type,
        'path': image_path,
        'llm_annotation': annotation,
        'explanations': str(explanation)
    })

df = pd.DataFrame(results_data)
df.to_csv('llm_annotation_4o.csv', index=False)

print(f"\nAnnotation complete! Processed {len(ad_images)} images.")
print("Results saved to:")
print("- llm_annotation_dict_4o.json")
print("- llm_annotation_explanations_4o.json") 
print("- llm_annotation_4o.csv")